### ISSUE TITLE
any downside to using mixins instead of this?

### ISSUE THREAD

**Issue by chessai** [haskell-hvr/base-noprelude#10]
eg. `mixins: base hiding (Prelude)`

If there is no downside, might it be recommended to use mixins for those cabal versions which support it? AFAIK base-noprelude isnt an official Haskell project so failure for upkeep means potential for breakage, while the mixins does not.

**Comment by hvr** [comment]
The huge downside for me is that ghc environment files don't support mixins yet; and also mixins don't work for all GHCs. That unfortunately means that mixins are not strictly better. As for the upkeep concern: I've been keeping this up for all `base` versions supported by cabal new-build, i.e. back till base-4.3.0.0 / GHC 7.0.1... and afaik I didn't screw up any of the `base-noprelude` releases so far ;-)

PS: Fwiw, I do mention the use of `mixins` at http://hackage.haskell.org/package/Prelude

**Comment by chessai** [comment]
Closing, since the question has been answered. Thanks!
