### ISSUE TITLE
Reexport Prelude with a different name

### ISSUE THREAD

**Issue by guibou** [haskell-hvr/base-noprelude#17]
I had problem using `base-noprelude` in my codebase because my custom `Prelude` was importing functions from the original prelude. Hence my codebase was depending on both `base` and `base-noprelude` which was leading to conflict in a few scenarios (for example, when building a repl with all the modules of the codebase).

In https://github.com/guibou/base-noprelude/commit/c5481041705d5a4ce43adfb99cd8bde5fc845d50 I experimented with reexporting `Prelude` as a different name (here, `BasePrelude`).

This way, a codebase which just want to override the basic `Prelude` can simply import it as long as `base-noprelude` is available, for example:

```haskell
module Prelude (module BasePrelude) where

import BasePrelude hiding (head)

-- | A safer head
head :: [a] -> Maybe a
head = ...
```

Instead of importing from `base` which will pull `base` in the dependencies of this module.

I'm mostly opening this issue for reference about my problem (and workaround), but if you release a new version of `base-noprelude`, I think it may be convenient to reexporte `Prelude` with a different name inside it.

**Comment by eyeinsky** [comment]
AFAIK, base-noprelude isn't required anymore. You can have a custom, base's-Prelude-overriding prelude with cabal mixins:
```haskell
  mixins:          base (Prelude as BasePrelude)
                 , base hiding (Prelude)
  exposed-modules: Prelude
```

And a Prelude.hs in your project:
```haskell
module Prelude
  ( module BasePrelude
  , module Prelude
  ) where

import BasePrelude

...
```

With the mixin you rename base's Prelude to BasePrelude, then in your custom Prelude import and export it, while being able to customize it.

**Comment by guibou** [comment]
@eyeinsky good point.

For those  who do not use cabal, the same thing can be achieved when passing flags to ghc. For example:

```
$ ghci -hide-all-packages -package "base (Data.Functor, Prelude as BasePrelude)"
GHCi, version 9.4.6: https://www.haskell.org/ghc/  :? for help
ghci> import Prelude

<no location info>: error:
    Could not load module ‘Prelude’
    It is a member of the hidden package ‘base-4.17.2.0’.
    You can run ‘:set -package base’ to expose it.
    (Note: this unloads all the modules in the current scope.)
ghci> import Data.Functor
ghci> import BasePrelude
```

Note, I'm unsure how to do the `hiding` thing, so actually I'm listing all the module from base I care about and I use `-hide-all-packages`.

I'm closing this ticket, there is an easy workaround which can be applied on all build system I'm aware of (because it simply uses ghc flags).
