### ISSUE TITLE
Update for GHC 8.4.1/base-4.11

### ISSUE THREAD

**Issue by 23Skidoo** [haskell-hvr/base-noprelude#8]
What it says on the tin. Also it looks like the 8.2.2/4.10.1.0 update wasn't pushed to GitHub.

**Comment by hvr** [comment]
base-4.10.1.0 pushed as 8be3d364afea1586e54aa9f5ed0c769047d69a8f

For base-4.11 I need to check whether I can get away w/ using cabal-version:2.0 (cause base-4.11 requires a Cabal 2.2 spec version; and I can't upload those yet to hackage before a redeployment)

**Comment by 23Skidoo** [comment]
Ah, so that's why `base-4.11` is not on Hackage yet.

**Comment by hvr** [comment]
Resolved via https://hackage.haskell.org/package/base-noprelude-4.11.0.0
